KEY_MAP = {
    # Letters
    "a": "a",
    "b": "b",
    "c": "c",
    "d": "d",
    "e": "e",
    "f": "f",
    "g": "g",
    "h": "h",
    "i": "i",
    "j": "j",
    "k": "k",
    "l": "l",
    "m": "m",
    "n": "n",
    "o": "o",
    "p": "p",
    "q": "q",
    "r": "r",
    "s": "s",
    "t": "t",
    "u": "u",
    "v": "v",
    "w": "w",
    "x": "x",
    "y": "y",
    "z": "z",
    # Numbers
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "0": "0",
    # Symbols
    "comma": ",",
    "dot": ".",
    "slash": "/",
    "semicolon": ";",
    "apostrophe": "'",
    "grave": "`",
    "left_bracket": "[",
    "right_bracket": "]",
    "backslash": "\\",
    "minus": "-",
    "equal": "=",
    # Modifiers & control
    "escape": "esc",
    "backspace": "backspace",
    "tab": "tab",
    "enter": "enter",
    "space": "space",
    "caps_lock": "caps lock",
    "num_lock": "num lock",
    "left_shift": "left shift",
    "right_shift": "right shift",
    "left_ctrl": "left ctrl",
    "right_ctrl": "right ctrl",
    "left_alt": "left alt",
    "right_alt": "right alt",
    # Navigation
    "home": "home",
    "end": "end",
    "page_up": "page up",
    "page_down": "page down",
    "insert": "insert",
    "delete": "delete",
    "up": "up",
    "down": "down",
    "left": "left",
    "right": "right",
    # Function keys
    "f1": "f1",
    "f2": "f2",
    "f3": "f3",
    "f4": "f4",
    "f5": "f5",
    "f6": "f6",
    "f7": "f7",
    "f8": "f8",
    "f9": "f9",
    "f10": "f10",
    "f11": "f11",
    "f12": "f12",
    # Numpad - might be broken? https://github.com/boppreh/keyboard/issues/161
    "numpad_0": "num 0",
    "numpad_1": "num 1",
    "numpad_2": "num 2",
    "numpad_3": "num 3",
    "numpad_4": "num 4",
    "numpad_5": "num 5",
    "numpad_6": "num 6",
    "numpad_7": "num 7",
    "numpad_8": "num 8",
    "numpad_9": "num 9",
    "numpad_dot": "num dot",
    "numpad_enter": "num enter",
    "numpad_plus": "num plus",
    "numpad_minus": "num minus",
    "numpad_multiply": "num multiply",
    "numpad_divide": "num divide",
    # Mouse buttons
    "mouse_left": "mouse left",
    "mouse_right": "mouse right",
    "mouse_middle": "mouse middle",
    "mouse_side": "mouse side",
    "mouse_extra": "mouse extra",
    "mouse_forward": "mouse forward",
    "mouse_back": "mouse back",
    "mouse_task": "mouse task",
}
